force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Reopen</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MilesotoneTriggerHelper.cls
public class MilesotoneTriggerHelper {

    public static void updateMilestoneStartDate(List<Milestone__c> newMilestone,Map<Id, Milestone__c> oldMap){
        try{
            for(Milestone__c milestoneRec : newMilestone){
                Milestone__c oldRec = oldMap.get(milestoneRec.Id);
                if(oldRec.Status__c != milestoneRec.Status__c &&
                   milestoneRec.Status__c == 'Completed'){
                    milestoneRec.Actual_End_Date__c = Date.today();
                }
            }
        }catch(Exception e){
            System.debug(' error message =====> ' + e.getMessage() + ' at Line number =====> ' + e.getLineNumber());
        }
    }
}