force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project.</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000}</displayFormat>
        <label>Project Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Employee_Cost_Based_On__c.field-meta.xml
<CustomField>
    <fullName>Employee_Cost_Based_On__c</fullName>
    <formula>(Employee_Cost__c * Allocation__c) / 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Cost Based On %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team Members</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tasks__c/Tasks__c.object-meta.xml
<CustomObject>
    <label>Tasks.</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tasks__c/fields/Actual_Hours__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours__c</fullName>
    <label>Actual Hours</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tasks__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Log__c/Time_Log__c.object-meta.xml
<CustomObject>
    <label>Time Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Time Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Log__c/fields/Cost_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cost_Amount__c</fullName>
    <label>Cost Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Time_Log__c/fields/Daily_Logs__c.field-meta.xml
<CustomField>
    <fullName>Daily_Logs__c</fullName>
    <label>Daily Logs</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Log__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Log__c/fields/Tasks__c.field-meta.xml
<CustomField>
    <fullName>Tasks__c</fullName>
    <label>Tasks</label>
    <referenceTo>Tasks__c</referenceTo>
    <relationshipLabel>Time Logs</relationshipLabel>
    <relationshipName>Time_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TimelogTriggerHandler.cls
public class TimelogTriggerHandler {
    public static void aggregateTimelogOnTask(List<Time_Log__c> listOfTimeLog,Map<Id,Time_Log__c> oldMap){
        try{
            set<Id> setOfTasksId = new set<Id>();
            for(Time_Log__c timeLogRec : listOfTimeLog){
                if(oldMap == null){
                    if(timeLogRec.Tasks__c != null){
                        setOfTasksId.add(timeLogRec.Tasks__c);
                    }
                }else{
                    Time_Log__c oldRec = oldMap.get(timeLogRec.Id);
                    if(timeLogRec.Tasks__c != null && (timeLogRec.Daily_Logs__c != oldRec.Daily_Logs__c || timeLogRec.Tasks__c != oldRec.Tasks__c)){
                        setOfTasksId.add(timeLogRec.Tasks__c);
                    }
                    if(oldRec.Tasks__c != null &&
                       timeLogRec.Tasks__c != oldRec.Tasks__c){
                           
                           setOfTasksId.add(oldRec.Tasks__c);
                       }
                }
            }
            if (!setOfTasksId.isEmpty()) {
                List<AggregateResult> aggregateTimeLogResults = [SELECT Tasks__c tId,SUM(Daily_Logs__c) totalLoggedHours 
                                                                 FROM Time_Log__c WHERE Tasks__c IN :setOfTasksId 
                                                                 GROUP BY Tasks__c];
                
                Map<Id, Decimal> tTotals = new Map<Id, Decimal>();
                
                for (AggregateResult ar : aggregateTimeLogResults) {
                    Id taskId = (Id) ar.get('tId');
                    Decimal totalHours = (Decimal) ar.get('totalLoggedHours');
                    tTotals.put(taskId, totalHours);
                }
                
                List<Tasks__c> tlUpdates = new List<Tasks__c>();
                
                for (Id taskId : tTotals.keySet()) {
                    tlUpdates.add(new Tasks__c(
                        Id = taskId,
                        Actual_Hours__c = tTotals.get(taskId)
                    ));
                }
                
                if (!tlUpdates.isEmpty()) {
                    update tlUpdates;
                }
            }
            
        }catch(exception e){
            system.debug(' error message =====>' + e.getMessage() + ' at line number ====>'+ e.getLineNumber());
        }
    } 
    
    public static void costRateOfUser(List<Time_Log__c> listOfTimeLog, Map<Id, Time_Log__c> oldMap) {
        try {
            Set<Id> setOfProjectId = new Set<Id>();
            
            for (Time_Log__c timeRec : listOfTimeLog) {
                if (timeRec.Projects__c != null) {
                    if (oldMap == null) {
                        setOfProjectId.add(timeRec.Projects__c);
                    } else {
                        Time_Log__c oldRec = oldMap.get(timeRec.Id);
                        if (timeRec.Projects__c != oldRec.Projects__c || 
                            timeRec.Daily_Logs__c != oldRec.Daily_Logs__c) {
                                setOfProjectId.add(timeRec.Projects__c);
                            }
                    }
                }
            }
            
            if (!setOfProjectId.isEmpty()) {
                Map<Id, Project_Team_Member__c> mapOfProjectToTeamMember = new Map<Id, Project_Team_Member__c>();
                for (Project_Team_Member__c prTeamRec : [SELECT Id, Assigned_To__c, Project__c, Employee_Cost_Based_On__c FROM Project_Team_Member__c WHERE Project__c IN :setOfProjectId AND Assigned_To__c = :UserInfo.getUserId()]) {
                    mapOfProjectToTeamMember.put(prTeamRec.Project__c, prTeamRec);
                }
                
                for (Time_Log__c timeRec : listOfTimeLog) {
                    if (timeRec.Projects__c != null && timeRec.Daily_Logs__c != null && mapOfProjectToTeamMember.containsKey(timeRec.Projects__c)) {
                        Decimal costRate = mapOfProjectToTeamMember.get(timeRec.Projects__c).Employee_Cost_Based_On__c;
                        timeRec.Cost_Amount__c = timeRec.Daily_Logs__c * costRate;
                    }
                }
            }
            
        } catch (Exception e) {
            System.debug('Error ====> ' + e.getMessage() + ' Line ====> ' + e.getLineNumber());
        }
    }
    
}