force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project.</label>
    <nameField>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick off</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>BRG</fullName>
            </value>
            <value>
                <fullName>Sign-off</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Go-Live</fullName>
            </value>
            <value>
                <fullName>Hypercare Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Stage_Task_Config__mdt/Project_Stage_Task_Config__mdt.object-meta.xml
<CustomObject>
    <label>Project Stage Task Config</label>
    <pluralLabel>Project Stage Task Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project_Stage_Task_Config__mdt/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <label>Owner Role</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Stage_Task_Config__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Stage_Task_Config__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Stage_Task_Config__mdt/fields/Task_Subject__c.field-meta.xml
<CustomField>
    <fullName>Task_Subject__c</fullName>
    <label>Task Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000}</displayFormat>
        <label>Project Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team Members</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Senior Developer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UI/UX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectStageTaskHandler.cls
public class ProjectStageTaskHandler {
    
    
    public static void validateProjectManager(
    List<Project__c> newList,
    Map<Id, Project__c> oldMap){

    Set<Id> projectIdsToCheck = new Set<Id>();

    for(Project__c proj : newList){

        // Moving TO Pre Kick off
        if(proj.Status__c == 'Pre Kick off' &&
           oldMap.get(proj.Id).Status__c != 'Pre Kick off'){

            projectIdsToCheck.add(proj.Id);
        }
    }

    if(projectIdsToCheck.isEmpty()) return;

    // Query Team Members
    List<Project_Team_Member__c> teamMembers =
        [SELECT Project__c
         FROM Project_Team_Member__c
         WHERE Project__c IN :projectIdsToCheck
         AND Role__c = 'Project Manager'];

    Set<Id> projectsWithPM = new Set<Id>();

    for(Project_Team_Member__c ptm : teamMembers){
        projectsWithPM.add(ptm.Project__c);
    }

    // Add error if missing
    for(Project__c proj : newList){

        if(projectIdsToCheck.contains(proj.Id) &&
           !projectsWithPM.contains(proj.Id)){

            proj.Status__c.addError(
                'Add Project Manager in Project Team Members before moving to Pre Kick off.'
            );
        }
    }
}

     public static void processProjects(List<Project__c> newList,
                                       Map<Id, Project__c> oldMap,
                                       Boolean isInsert){

        Set<String> stagesToProcess = new Set<String>();
        List<Project__c> projectsToProcess = new List<Project__c>();

        for(Project__c proj : newList){

            if(isInsert){
                if(proj.Status__c != null){
                    stagesToProcess.add(proj.Status__c);
                    projectsToProcess.add(proj);
                }
            }
            else{
                if(proj.Status__c != oldMap.get(proj.Id).Status__c){
                    if(proj.Status__c != null){
                        stagesToProcess.add(proj.Status__c);
                        projectsToProcess.add(proj);
                    }
                }
            }
        }

        if(projectsToProcess.isEmpty()) return;


        List<Project_Stage_Task_Config__mdt> metaList =
            [SELECT Status__c,
                    Task_Subject__c,
                    Owner_Role__c,
                    Sequence__c
             FROM Project_Stage_Task_Config__mdt
             WHERE Status__c IN :stagesToProcess
             AND Is_Active__c = TRUE
             ORDER BY Sequence__c ASC];


        Set<Id> projectIds = new Set<Id>();
        for(Project__c p : projectsToProcess){
            projectIds.add(p.Id);
        }


        List<Project_Team_Member__c> teamMembers =
            [SELECT Project__c, Role__c, Assigned_To__c
             FROM Project_Team_Member__c
             WHERE Project__c IN :projectIds];

      
        Map<String, Id> projectRoleUserMap = new Map<String, Id>();

        for(Project_Team_Member__c ptm : teamMembers){
            if(ptm.Assigned_To__c != null && ptm.Role__c != null){
                String key = ptm.Project__c + '-' + ptm.Role__c;
                projectRoleUserMap.put(key, ptm.Assigned_To__c);
            }
        }

        List<Task> tasksToInsert = new List<Task>();

        for(Project__c proj : projectsToProcess){

            for(Project_Stage_Task_Config__mdt meta : metaList){

                if(proj.Status__c == meta.Status__c){

                    Task t = new Task();
                    t.Subject = meta.Task_Subject__c;
                    t.WhatId = proj.Id;
                    t.Status = 'Not Started';
                    t.Priority = 'Normal';

                    String mapKey = proj.Id + '-' + meta.Owner_Role__c;

                    if(projectRoleUserMap.containsKey(mapKey)){
                        t.OwnerId = projectRoleUserMap.get(mapKey);
                    } else {
                        t.OwnerId = proj.OwnerId;
                    }

                    tasksToInsert.add(t);
                }
            }
        }

        if(!tasksToInsert.isEmpty()){
            insert tasksToInsert;
        }
    }
}