force-app/main/default/objects/Issue_Bug__c/Issue_Bug__c.object-meta.xml
<CustomObject>
    <label>Issue/Bug</label>
    <nameField>
        <label>Issue/Bug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues/Bugs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Bug__c/fields/Issue_Bug__c.field-meta.xml
<CustomField>
    <fullName>Issue_Bug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue/Bug</label>
    <referenceTo>Issue_Bug__c</referenceTo>
    <relationshipLabel>Issues/Bugs</relationshipLabel>
    <relationshipName>Issues_Bugs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Bug__c/fields/Retesting_Count__c.field-meta.xml
<CustomField>
    <fullName>Retesting_Count__c</fullName>
    <label>Retesting Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Issue_Bug__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Blocker</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>To be Tested</fullName>
            </value>
            <value>
                <fullName>In Retest</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IssueBugHandler.cls
public with sharing class IssueBugHandler {
	  public static void updateRetestCount(
        List<Issue_Bug__c> newList,
        Map<Id, Issue_Bug__c> oldMap
    ) {

        for (Issue_Bug__c newRec : newList) {

            Issue_Bug__c oldRec = oldMap.get(newRec.Id);

           if (oldRec.Status__c != 'In Retest' &&
                newRec.Status__c == 'In Retest') {

                if (newRec.Retesting_Count__c == null) {
                    newRec.Retesting_Count__c = 1;
                } else {
                    newRec.Retesting_Count__c += 1;
                }
            }
        }
    }
}