force-app/main/default/objects/Tasks__c/Tasks__c.object-meta.xml
<CustomObject>
    <label>Tasks.</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tasks__c/fields/Associated_Project__c.field-meta.xml
<CustomField>
    <fullName>Associated_Project__c</fullName>
    <label>Associated Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tasks__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeamLeadDashboardController.cls
public with sharing class TeamLeadDashboardController {
    
  public class SummaryMetrics {
        @AuraEnabled public Integer teamTasksDueToday;
        @AuraEnabled public Integer dueThisWeek;
        @AuraEnabled public Integer overdueTeam;
        @AuraEnabled public Integer s1s2BugsOpen;
    }
 
    @AuraEnabled(cacheable=true)
    public static SummaryMetrics getSummaryMetrics(Id projectId) {
        
        SummaryMetrics result = new SummaryMetrics();
        Date today = Date.today();
        
   
        Date startOfWeek = today.toStartOfWeek();
        Date endOfWeek   = startOfWeek.addDays(6);
        
 
            result.teamTasksDueToday = [
            SELECT COUNT() FROM Tasks__c WHERE End_Date__c = :today AND Status__c NOT IN ('Testing', 'Completed') AND Associated_Project__c = :projectId];
        
 
        result.dueThisWeek = [
            SELECT COUNT()
            FROM Tasks__c WHERE End_Date__c >= :startOfWeek AND End_Date__c <= :endOfWeek AND Status__c NOT IN ('Testing', 'Completed') AND Associated_Project__c = :projectId
        ];
        
        result.overdueTeam = [
            SELECT COUNT() FROM Tasks__c WHERE End_Date__c < :today AND Status__c NOT IN ('Testing', 'Completed') AND Associated_Project__c = :projectId];
        return result;
    }
  }